<GetStartedScreen>:
    FloatLayout:
        canvas:
            Rectangle:
                source: 'assets/background.png'
                size: self.size
                pos: self.pos

        Button:
            background_normal: 'assets/get_started_button.png'
            background_down: 'assets/get_started_button.png'
            size_hint: 0.6, 0.1
            pos_hint: {'center_x': 0.5, 'y': 0.1}
            on_press: app.root.current = 'main'
